mysql_mybosoft:
  image: mysql:5.7
  command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - 3306:3306
repository:
  build: /vagrant/Notifications/repository
  ports:
    - 8090:8080
    - 8000:8000
  links:
   - mysql_mybosoft
loader:
  build: /vagrant/Notifications/loader
  ports:
    - 8091:8080
    - 8001:8000
  links:
   - mysql_mybosoft
   - repository
exchange:
  build: /vagrant/Notifications/exchange
  ports:
    - 8092:8080
    - 8002:8000
  links:
    - mysql_mybosoft
    - repository
surveys:
  build: /vagrant/Notifications/surveys
  ports:
    - 8093:8080
    - 8003:8000
  links:
    - mysql_mybosoft
    - repository
rentsense:
  build: /vagrant/Legacy/rentsense
  ports:
    - 8080:8080
    - 8004:8000
  links:
    - mysql_mybosoft
irr:
  build: /vagrant/IRR
  ports:
    - 8081:8080
    - 8005:8000
  links:
    - mysql_mybosoft
    - rentsense
bi:
  build: /vagrant/Legacy/bi
  ports:
    - 8082:8080
    - 8006:8000
  links:
    - mysql_mybosoft
    - rentsense